apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: eingaruca/django:v1  # Reemplaza esto con la ubicación de tu imagen Docker
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8000
